apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: fluxguard-events
  namespace: fluxguard
  labels:
    strimzi.io/cluster: fluxguard-kafka
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: fluxguard-anomalies
  namespace: fluxguard
  labels:
    strimzi.io/cluster: fluxguard-kafka
spec:
  partitions: 3
  replicas: 1